<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYyLd5Uq\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYyLd5Uq/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYyLd5Uq.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYyLd5Uq\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYyLd5Uq\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'YyLd5Uq',
    'container.build_id' => '0b824b64',
    'container.build_time' => 1639402275,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYyLd5Uq');
